CREATE TABLE ROCM_DIGITAL_OPPTY
  (
    OPPTY_ID             NUMBER(18) NOT NULL ,
    OPPTY_SRC_CD         VARCHAR2(10) NOT NULL ,
    PGM_CD               VARCHAR2(10) NOT NULL ,
    SUB_PGM_CD           VARCHAR2(17) NOT NULL ,
    DELIVERY_DT          DATE NOT NULL ,
    OPPTY_EXPN_DT        DATE NOT NULL ,
    ROCM_CYCLE_NBR       NUMBER(10) NOT NULL ,
    OPPTY_STATUS_CD      NUMBER(10) NOT NULL ,
    OPPTY_SUB_STATUS_CD  NUMBER(10) NOT NULL ,
    OPPTY_RANK_NBR       NUMBER(10) NOT NULL ,
    MEMEBER_TYP_CD       VARCHAR2(30) NOT NULL ,
    MEMBER_ID            VARCHAR2(30) NOT NULL ,
    CAMPAIGN_ID          VARCHAR2(30) ,
    EVENT_NM_TXT         VARCHAR2(100) ,
    SUB_CAMPAIGN_TYP_TXT VARCHAR2(100) ,
    CONTACT_TYP_CD       VARCHAR2(30) NOT NULL ,
    CONTACT_TYP_ID       VARCHAR2(100) ,
    EMAIL_SUBJECT_TXT    VARCHAR2(200) ,
    EMAIL_PREVIEW_TXT    VARCHAR2(200) ,
    SRC_CYCLE_NBR        NUMBER(10),
    WKFLW_EXECN_ID       NUMBER(18) NOT NULL ,
    WKFLW_EXECN_DT       DATE NOT NULL ,
    ODATE                DATE NOT NULL ,
    SRC_WKFLW_EXECN_ID   NUMBER(18) NOT NULL ,
    PRIMARY KEY (OPPTY_ID,OPPTY_SRC_CD)
  )
  STORAGE
  (
    INITIAL 100K NEXT 50K
  )
  LOGGING PARTITION BY RANGE( ODATE)
  (
    PARTITION ODATE_q1_2006 VALUES LESS THAN (TO_DATE('01-APR-2021','dd-MON-yyyy')) TABLESPACE tsa STORAGE (INITIAL 20K NEXT 10K) ,
    PARTITION ODATE_q2_2006 VALUES LESS THAN (TO_DATE('01-JUL-2021','dd-MON-yyyy')) TABLESPACE tsb ,
    PARTITION ODATE_q3_2006 VALUES LESS THAN (TO_DATE('01-OCT-2021','dd-MON-yyyy')) TABLESPACE tsc ,
    PARTITION ODATE_q4_2006 VALUES LESS THAN (TO_DATE('01-JAN-2022','dd-MON-yyyy')) TABLESPACE tsd
  )
  ENABLE ROW MOVEMENT; 
 ---------------------------------------------------------------------------------------------------
  CREATE TABLE ROCM_DIGITAL_OPPTY_ADDL_DTL
  (
    OPPTY_ADDL_SEQ_ID  NUMBER(18) NOT NULL,
    OPPTY_ID           NUMBER(18) NOT NULL ,
    OPPTY_SRC_CD       VARCHAR2(20) NOT NULL ,
    PGM_CD             VARCHAR2(10) NOT NULL ,
    SUB_PGM_CD         VARCHAR2(17) NOT NULL ,
    SGMNT_CD_LVL1      VARCHAR2(100) NOT NULL,
    SGMNT_CD_LVL2      VARCHAR2(100) ,
    SGMNT_CD_LVL3      VARCHAR2(100) ,
    SGMNT_CD_LVL4      VARCHAR2(100) ,
    SGMNT_CD_LVL5      VARCHAR2(100) ,
    SGMNT_CD_LVL6      VARCHAR2(100) ,
    SGMNT_SEQ_NBR      NUMBER(5) NOT NULL ,
    ATRB_NM1           VARCHAR2(100) NOT NULL ,
    ATRB_VAL1          VARCHAR2(1000) NOT NULL ,
    ATRB_NM2           VARCHAR2(100) ,
    ATRB_VAL2          VARCHAR2(1000) ,
    ATRB_NM3           VARCHAR2(100) ,
    ATRB_VAL3          VARCHAR2(1000) ,
    ATRB_NM4           VARCHAR2(100) ,
    ATRB_VAL4          VARCHAR2(1000) ,
    ATRB_NM5           VARCHAR2(100) ,
    ATRB_VAL5          VARCHAR2(1000) ,
    ATRB_NM6           VARCHAR2(100) ,
    ATRB_VAL6          VARCHAR2(1000) ,
    ATRB_NM7           VARCHAR2(100) ,
    ATRB_VAL7          VARCHAR2(1000) ,
    ATRB_NM8           VARCHAR2(100) ,
    ATRB_VAL8          VARCHAR2(1000) ,
    ATRB_NM9           VARCHAR2(100) ,
    ATRB_VAL9          VARCHAR2(1000) ,
    ATRB_NM10          VARCHAR2(100) ,
    ATRB_VAL10         VARCHAR2(1000) ,
    WKFLW_EXECN_ID     NUMBER( 18) NOT NULL ,
    WKFLW_EXECN_DT     DATE NOT NULL ,
    ODATE              DATE NOT NULL ,
    SRC_WKFLW_EXECN_ID NUMBER(18) NOT NULL,
    PRIMARY KEY (OPPTY_ADDL_SEQ_ID)
  )
  STORAGE
  (
    INITIAL 100K NEXT 50K
  )
  LOGGING PARTITION BY RANGE
  (
    ODATE
  )
  (
    PARTITION ODATE_q1_2006 VALUES LESS THAN (TO_DATE('01-APR-2021','dd-MON-yyyy')) TABLESPACE tsa STORAGE (INITIAL 20K NEXT 10K) ,
    PARTITION ODATE_q2_2006 VALUES LESS THAN (TO_DATE('01-JUL-2021','dd-MON-yyyy')) TABLESPACE tsb ,
    PARTITION ODATE_q3_2006 VALUES LESS THAN (TO_DATE('01-OCT-2021','dd-MON-yyyy')) TABLESPACE tsc ,
    PARTITION ODATE_q4_2006 VALUES LESS THAN (TO_DATE('01-JAN-2022','dd-MON-yyyy')) TABLESPACE tsd
  )
  ENABLE ROW MOVEMENT;
  
  alter table
   ROCM_DIGITAL_OPPTY_ADDL_DTL
modify
(
   OPPTY_SRC_CD    varchar2(30)
);

  